### ISSUE TITLE
How do people insert the data initially?

### ISSUE THREAD

**Issue by jkup** [jkup/credentials#5]
@guyoron:
Say you have MySQL credentials like in the README example. How do you get those into CREDENTIAL_KEY or CREDENTIAL_OBJ? Should we have a command line utility? Or should people have to manually insert them into the file and then credentials.js can read them?

**Comment by guyoron** [comment]
Command line utility would be nice, but I think to start with it's fine if people have to enter them in manually.

**Comment by jkup** [comment]
Ok I'm going to take that approach for now. I'll probably make a ticket to build an accompanying CLI utility.. but for now I'll just add mine manually. I'm going to try to work on this more tomorrow.
